# Generated by Django 6.0.3 on 2026-03-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unisex', 'Unisex')], default='female', max_length=10),
        ),
    ]
